{
  "comments": [
    {
      "key": {
        "uuid": "0a4c9d60_acd67d71",
        "filename": "src/MathWikibaseConfig.php",
        "patchSetId": 1
      },
      "lineNbr": 136,
      "author": {
        "id": 183
      },
      "writtenOn": "2019-11-26T17:49:15Z",
      "side": 1,
      "message": "Is that the most specific exception it throws?",
      "revId": "7a510be15c3bb1d403d1d973284bcccd7e0346e2",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8567fce2_892b9651",
        "filename": "src/MathWikibaseConnector.php",
        "patchSetId": 1
      },
      "lineNbr": 222,
      "author": {
        "id": 183
      },
      "writtenOn": "2019-11-26T17:49:15Z",
      "side": 1,
      "message": "please log the error",
      "revId": "7a510be15c3bb1d403d1d973284bcccd7e0346e2",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951",
      "unresolved": false
    }
  ]
}